services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1 #version 7.5.0 is available
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    networks:
      - taxi_network
    #healthcheck:
    #test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
    #interval: 10s
    #timeout: 5s
    #retries: 5

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      #KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    #restart: unless-stopped
    networks:
      - taxi_network

  python-producer:
    build:
      context: ./taxi_locations/producer
      dockerfile: Dockerfile
    volumes:
      - ./taxi_locations:/app
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_BROKER: kafka:29092
    restart: unless-stopped
    networks:
      - taxi_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - taxi_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - taxi_network

  
  flink-jobmanager:
    image: flink:1.18.1-scala_2.12-java17
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager        

    command: jobmanager
    restart: unless-stopped
    networks:
      - taxi_network

  
  flink-taskmanager:
    image: flink:1.18.1-scala_2.12-java17
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 5  
    restart: unless-stopped
    networks:
      - taxi_network


networks:
  taxi_network:
    driver: bridge